In [1]:
import numpy as np

In [3]:
import funciones as mifun

In [4]:
mifun.saludar()

Hola mundo!


In [5]:
lista = [ 1 , 2, 3, 4, False, 'Hola']

In [6]:
print(lista)

[1, 2, 3, 4, False, 'Hola']


In [7]:
array1 = np.array(lista)

In [8]:
type(lista)

list

In [9]:
type(array1)

numpy.ndarray

In [10]:
print(array1) 

['1' '2' '3' '4' 'False' 'Hola']


Si comparamos, la **lista mantiene los tipos de dato de los elementos** de la lista pero cuando numpy los convierte a **array lo pasa a string**. Los arrays de numpy no son tan flexibles como las listas, es decir si tengo solo floats, los elementos seran floats.

In [12]:
array2 = np.array([4,6,7,8,432]) #Array enteros
print(array2)

[  4   6   7   8 432]


In [14]:
array3 = np.array([ 4 , 2 , 2.6 , 465 ]) ## mostramos que promociana al tipo que pueda contener todos los datos
print(array3)

[  4.    2.    2.6 465. ]


In [16]:
array4= np.array([4 , 6 , 8 ,2+2+2, False, True]) #False y true los conviere en o y q
print(array4)

[4 6 8 6 0 1]


In [17]:
#Creo una matriz de ceros
print(np.zeros((10,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
print(np.eye(5)) #Creo la matriz identidad

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
print(np.eye(5)*8) 

[[8. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0.]
 [0. 0. 8. 0. 0.]
 [0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 8.]]


Usamos las matrices para imagenes, y a su vez tenemos que entender que algunos datos van a venir representados de forma matricial.

In [21]:
valores = [4, 6, 7, 10, 33, 100, -45]

#Como hago para encontrar el valor maximo?
max = valores[0]
for x in valores[1:]:
    if x > max:
        max = x

print(max)


100


In [23]:
#Pero esto numpy ya lo puede hacer
val = np.array(valores)
print(val.max())
print(val.min())

100
-45


Numpy me permite mutilplicar los elementos, a diferencia de la lista que lo repite

In [24]:
print(val * 3)
print([1 , 2, 3, 4]*3)

[  12   18   21   30   99  300 -135]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [25]:
lnum = [4, 6 , 10, 11]
print(lnum[2:])
print(val[2:])

[10, 11]
[  7  10  33 100 -45]


Los slices funcionan de igual forma en las listas y en los arrays de numpy

In [26]:
cuadrado = np.ones((8,8))
cuadrado

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
cuadrado[1:-1,1:-1] = 0 # va a agregar ceros
cuadrado

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])